//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifikasiFID.ServiceDOC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDOC.ServiceDocSoap")]
    public interface ServiceDocSoap {
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile3", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.PutFile3Response PutFile3(SimplifikasiFID.ServiceDOC.PutFile3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile3", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFile3Response> PutFile3Async(SimplifikasiFID.ServiceDOC.PutFile3Request request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile2", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.PutFile2Response PutFile2(SimplifikasiFID.ServiceDOC.PutFile2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile2", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFile2Response> PutFile2Async(SimplifikasiFID.ServiceDOC.PutFile2Request request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.PutFileResponse PutFile(SimplifikasiFID.ServiceDOC.PutFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFileResponse> PutFileAsync(SimplifikasiFID.ServiceDOC.PutFileRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileId", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.GetFileIdResponse GetFileId(SimplifikasiFID.ServiceDOC.GetFileIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileId", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileIdResponse> GetFileIdAsync(SimplifikasiFID.ServiceDOC.GetFileIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData2", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.GetFileData2Response GetFileData2(SimplifikasiFID.ServiceDOC.GetFileData2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData2", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileData2Response> GetFileData2Async(SimplifikasiFID.ServiceDOC.GetFileData2Request request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.GetFileDataResponse GetFileData(SimplifikasiFID.ServiceDOC.GetFileDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileDataResponse> GetFileDataAsync(SimplifikasiFID.ServiceDOC.GetFileDataRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileDataById", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.GetFileDataByIdResponse GetFileDataById(SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileDataById", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileDataByIdResponse> GetFileDataByIdAsync(SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFile", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.DeleteFileResponse DeleteFile(SimplifikasiFID.ServiceDOC.DeleteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFileResponse> DeleteFileAsync(SimplifikasiFID.ServiceDOC.DeleteFileRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFileById", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.DeleteFileByIdResponse DeleteFileById(SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFileById", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFileByIdResponse> DeleteFileByIdAsync(SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFilePreById", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponse DeleteFilePreById(SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFilePreById", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponse> DeleteFilePreByIdAsync(SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveFileById", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.MoveFileByIdResponse MoveFileById(SimplifikasiFID.ServiceDOC.MoveFileByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveFileById", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.MoveFileByIdResponse> MoveFileByIdAsync(SimplifikasiFID.ServiceDOC.MoveFileByIdRequest request);
        
        // CODEGEN: Generating message contract since element name JsonID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMergePdfFile", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.GetMergePdfFileResponse GetMergePdfFile(SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMergePdfFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetMergePdfFileResponse> GetMergePdfFileAsync(SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Organize", ReplyAction="*")]
        SimplifikasiFID.ServiceDOC.OrganizeResponse Organize(SimplifikasiFID.ServiceDOC.OrganizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Organize", ReplyAction="*")]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.OrganizeResponse> OrganizeAsync(SimplifikasiFID.ServiceDOC.OrganizeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile3", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.PutFile3RequestBody Body;
        
        public PutFile3Request() {
        }
        
        public PutFile3Request(SimplifikasiFID.ServiceDOC.PutFile3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrgFileName;
        
        public PutFile3RequestBody() {
        }
        
        public PutFile3RequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
            this.OrgFileName = OrgFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile3Response", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.PutFile3ResponseBody Body;
        
        public PutFile3Response() {
        }
        
        public PutFile3Response(SimplifikasiFID.ServiceDOC.PutFile3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFile3Result;
        
        public PutFile3ResponseBody() {
        }
        
        public PutFile3ResponseBody(string PutFile3Result) {
            this.PutFile3Result = PutFile3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile2", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.PutFile2RequestBody Body;
        
        public PutFile2Request() {
        }
        
        public PutFile2Request(SimplifikasiFID.ServiceDOC.PutFile2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrgFileName;
        
        public PutFile2RequestBody() {
        }
        
        public PutFile2RequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
            this.OrgFileName = OrgFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile2Response", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.PutFile2ResponseBody Body;
        
        public PutFile2Response() {
        }
        
        public PutFile2Response(SimplifikasiFID.ServiceDOC.PutFile2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFile2Result;
        
        public PutFile2ResponseBody() {
        }
        
        public PutFile2ResponseBody(string PutFile2Result) {
            this.PutFile2Result = PutFile2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.PutFileRequestBody Body;
        
        public PutFileRequest() {
        }
        
        public PutFileRequest(SimplifikasiFID.ServiceDOC.PutFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        public PutFileRequestBody() {
        }
        
        public PutFileRequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.PutFileResponseBody Body;
        
        public PutFileResponse() {
        }
        
        public PutFileResponse(SimplifikasiFID.ServiceDOC.PutFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFileResult;
        
        public PutFileResponseBody() {
        }
        
        public PutFileResponseBody(string PutFileResult) {
            this.PutFileResult = PutFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileId", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileIdRequestBody Body;
        
        public GetFileIdRequest() {
        }
        
        public GetFileIdRequest(SimplifikasiFID.ServiceDOC.GetFileIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileIdRequestBody() {
        }
        
        public GetFileIdRequestBody(string source, string key1, string key2, int key3, int key4, int revision) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileIdResponseBody Body;
        
        public GetFileIdResponse() {
        }
        
        public GetFileIdResponse(SimplifikasiFID.ServiceDOC.GetFileIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetFileIdResult;
        
        public GetFileIdResponseBody() {
        }
        
        public GetFileIdResponseBody(int GetFileIdResult) {
            this.GetFileIdResult = GetFileIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileData2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData2", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileData2RequestBody Body;
        
        public GetFileData2Request() {
        }
        
        public GetFileData2Request(SimplifikasiFID.ServiceDOC.GetFileData2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileData2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileData2RequestBody() {
        }
        
        public GetFileData2RequestBody(string source, string key1, string key2, int key3, int key4, int revision) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileData2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData2Response", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileData2ResponseBody Body;
        
        public GetFileData2Response() {
        }
        
        public GetFileData2Response(SimplifikasiFID.ServiceDOC.GetFileData2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileData2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileData2Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentType;
        
        public GetFileData2ResponseBody() {
        }
        
        public GetFileData2ResponseBody(byte[] GetFileData2Result, string contentType) {
            this.GetFileData2Result = GetFileData2Result;
            this.contentType = contentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileDataRequestBody Body;
        
        public GetFileDataRequest() {
        }
        
        public GetFileDataRequest(SimplifikasiFID.ServiceDOC.GetFileDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileDataRequestBody() {
        }
        
        public GetFileDataRequestBody(string source, string key1, string key2, int key3, int key4, int revision) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileDataResponseBody Body;
        
        public GetFileDataResponse() {
        }
        
        public GetFileDataResponse(SimplifikasiFID.ServiceDOC.GetFileDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileDataResult;
        
        public GetFileDataResponseBody() {
        }
        
        public GetFileDataResponseBody(byte[] GetFileDataResult) {
            this.GetFileDataResult = GetFileDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataById", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileDataByIdRequestBody Body;
        
        public GetFileDataByIdRequest() {
        }
        
        public GetFileDataByIdRequest(SimplifikasiFID.ServiceDOC.GetFileDataByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetFileDataByIdRequestBody() {
        }
        
        public GetFileDataByIdRequestBody(int Id, string username, string password) {
            this.Id = Id;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetFileDataByIdResponseBody Body;
        
        public GetFileDataByIdResponse() {
        }
        
        public GetFileDataByIdResponse(SimplifikasiFID.ServiceDOC.GetFileDataByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileDataByIdResult;
        
        public GetFileDataByIdResponseBody() {
        }
        
        public GetFileDataByIdResponseBody(byte[] GetFileDataByIdResult) {
            this.GetFileDataByIdResult = GetFileDataByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFile", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.DeleteFileRequestBody Body;
        
        public DeleteFileRequest() {
        }
        
        public DeleteFileRequest(SimplifikasiFID.ServiceDOC.DeleteFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string delUser;
        
        public DeleteFileRequestBody() {
        }
        
        public DeleteFileRequestBody(string source, string key1, string key2, int key3, int key4, int revision, string delUser) {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.DeleteFileResponseBody Body;
        
        public DeleteFileResponse() {
        }
        
        public DeleteFileResponse(SimplifikasiFID.ServiceDOC.DeleteFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileResult;
        
        public DeleteFileResponseBody() {
        }
        
        public DeleteFileResponseBody(string DeleteFileResult) {
            this.DeleteFileResult = DeleteFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileById", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.DeleteFileByIdRequestBody Body;
        
        public DeleteFileByIdRequest() {
        }
        
        public DeleteFileByIdRequest(SimplifikasiFID.ServiceDOC.DeleteFileByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        public DeleteFileByIdRequestBody() {
        }
        
        public DeleteFileByIdRequestBody(int Id, string username, string password, string delUser) {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.DeleteFileByIdResponseBody Body;
        
        public DeleteFileByIdResponse() {
        }
        
        public DeleteFileByIdResponse(SimplifikasiFID.ServiceDOC.DeleteFileByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileByIdResult;
        
        public DeleteFileByIdResponseBody() {
        }
        
        public DeleteFileByIdResponseBody(string DeleteFileByIdResult) {
            this.DeleteFileByIdResult = DeleteFileByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilePreByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilePreById", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequestBody Body;
        
        public DeleteFilePreByIdRequest() {
        }
        
        public DeleteFilePreByIdRequest(SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilePreByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        public DeleteFilePreByIdRequestBody() {
        }
        
        public DeleteFilePreByIdRequestBody(int Id, string username, string password, string delUser) {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilePreByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilePreByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponseBody Body;
        
        public DeleteFilePreByIdResponse() {
        }
        
        public DeleteFilePreByIdResponse(SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilePreByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFilePreByIdResult;
        
        public DeleteFilePreByIdResponseBody() {
        }
        
        public DeleteFilePreByIdResponseBody(string DeleteFilePreByIdResult) {
            this.DeleteFilePreByIdResult = DeleteFilePreByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveFileByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveFileById", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.MoveFileByIdRequestBody Body;
        
        public MoveFileByIdRequest() {
        }
        
        public MoveFileByIdRequest(SimplifikasiFID.ServiceDOC.MoveFileByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveFileByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OldKey2;
        
        public MoveFileByIdRequestBody() {
        }
        
        public MoveFileByIdRequestBody(int Id, string username, string password, string delUser, string OldKey2) {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
            this.OldKey2 = OldKey2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveFileByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveFileByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.MoveFileByIdResponseBody Body;
        
        public MoveFileByIdResponse() {
        }
        
        public MoveFileByIdResponse(SimplifikasiFID.ServiceDOC.MoveFileByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveFileByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MoveFileByIdResult;
        
        public MoveFileByIdResponseBody() {
        }
        
        public MoveFileByIdResponseBody(string MoveFileByIdResult) {
            this.MoveFileByIdResult = MoveFileByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMergePdfFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMergePdfFile", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetMergePdfFileRequestBody Body;
        
        public GetMergePdfFileRequest() {
        }
        
        public GetMergePdfFileRequest(SimplifikasiFID.ServiceDOC.GetMergePdfFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMergePdfFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JsonID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetMergePdfFileRequestBody() {
        }
        
        public GetMergePdfFileRequestBody(string JsonID, string username, string password) {
            this.JsonID = JsonID;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMergePdfFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMergePdfFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.GetMergePdfFileResponseBody Body;
        
        public GetMergePdfFileResponse() {
        }
        
        public GetMergePdfFileResponse(SimplifikasiFID.ServiceDOC.GetMergePdfFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMergePdfFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetMergePdfFileResult;
        
        public GetMergePdfFileResponseBody() {
        }
        
        public GetMergePdfFileResponseBody(byte[] GetMergePdfFileResult) {
            this.GetMergePdfFileResult = GetMergePdfFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Organize", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.OrganizeRequestBody Body;
        
        public OrganizeRequest() {
        }
        
        public OrganizeRequest(SimplifikasiFID.ServiceDOC.OrganizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        public OrganizeRequestBody() {
        }
        
        public OrganizeRequestBody(string source) {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrganizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimplifikasiFID.ServiceDOC.OrganizeResponseBody Body;
        
        public OrganizeResponse() {
        }
        
        public OrganizeResponse(SimplifikasiFID.ServiceDOC.OrganizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OrganizeResult;
        
        public OrganizeResponseBody() {
        }
        
        public OrganizeResponseBody(int OrganizeResult) {
            this.OrganizeResult = OrganizeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDocSoapChannel : SimplifikasiFID.ServiceDOC.ServiceDocSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDocSoapClient : System.ServiceModel.ClientBase<SimplifikasiFID.ServiceDOC.ServiceDocSoap>, SimplifikasiFID.ServiceDOC.ServiceDocSoap {
        
        public ServiceDocSoapClient() {
        }
        
        public ServiceDocSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDocSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDocSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDocSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.PutFile3Response SimplifikasiFID.ServiceDOC.ServiceDocSoap.PutFile3(SimplifikasiFID.ServiceDOC.PutFile3Request request) {
            return base.Channel.PutFile3(request);
        }
        
        public string PutFile3(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            SimplifikasiFID.ServiceDOC.PutFile3Request inValue = new SimplifikasiFID.ServiceDOC.PutFile3Request();
            inValue.Body = new SimplifikasiFID.ServiceDOC.PutFile3RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            SimplifikasiFID.ServiceDOC.PutFile3Response retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).PutFile3(inValue);
            return retVal.Body.PutFile3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFile3Response> SimplifikasiFID.ServiceDOC.ServiceDocSoap.PutFile3Async(SimplifikasiFID.ServiceDOC.PutFile3Request request) {
            return base.Channel.PutFile3Async(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFile3Response> PutFile3Async(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            SimplifikasiFID.ServiceDOC.PutFile3Request inValue = new SimplifikasiFID.ServiceDOC.PutFile3Request();
            inValue.Body = new SimplifikasiFID.ServiceDOC.PutFile3RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).PutFile3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.PutFile2Response SimplifikasiFID.ServiceDOC.ServiceDocSoap.PutFile2(SimplifikasiFID.ServiceDOC.PutFile2Request request) {
            return base.Channel.PutFile2(request);
        }
        
        public string PutFile2(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            SimplifikasiFID.ServiceDOC.PutFile2Request inValue = new SimplifikasiFID.ServiceDOC.PutFile2Request();
            inValue.Body = new SimplifikasiFID.ServiceDOC.PutFile2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            SimplifikasiFID.ServiceDOC.PutFile2Response retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).PutFile2(inValue);
            return retVal.Body.PutFile2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFile2Response> SimplifikasiFID.ServiceDOC.ServiceDocSoap.PutFile2Async(SimplifikasiFID.ServiceDOC.PutFile2Request request) {
            return base.Channel.PutFile2Async(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFile2Response> PutFile2Async(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName) {
            SimplifikasiFID.ServiceDOC.PutFile2Request inValue = new SimplifikasiFID.ServiceDOC.PutFile2Request();
            inValue.Body = new SimplifikasiFID.ServiceDOC.PutFile2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).PutFile2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.PutFileResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.PutFile(SimplifikasiFID.ServiceDOC.PutFileRequest request) {
            return base.Channel.PutFile(request);
        }
        
        public string PutFile(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data) {
            SimplifikasiFID.ServiceDOC.PutFileRequest inValue = new SimplifikasiFID.ServiceDOC.PutFileRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.PutFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            SimplifikasiFID.ServiceDOC.PutFileResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).PutFile(inValue);
            return retVal.Body.PutFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFileResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.PutFileAsync(SimplifikasiFID.ServiceDOC.PutFileRequest request) {
            return base.Channel.PutFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.PutFileResponse> PutFileAsync(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data) {
            SimplifikasiFID.ServiceDOC.PutFileRequest inValue = new SimplifikasiFID.ServiceDOC.PutFileRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.PutFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).PutFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.GetFileIdResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileId(SimplifikasiFID.ServiceDOC.GetFileIdRequest request) {
            return base.Channel.GetFileId(request);
        }
        
        public int GetFileId(string source, string key1, string key2, int key3, int key4, int revision) {
            SimplifikasiFID.ServiceDOC.GetFileIdRequest inValue = new SimplifikasiFID.ServiceDOC.GetFileIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileIdRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            SimplifikasiFID.ServiceDOC.GetFileIdResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileId(inValue);
            return retVal.Body.GetFileIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileIdResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileIdAsync(SimplifikasiFID.ServiceDOC.GetFileIdRequest request) {
            return base.Channel.GetFileIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileIdResponse> GetFileIdAsync(string source, string key1, string key2, int key3, int key4, int revision) {
            SimplifikasiFID.ServiceDOC.GetFileIdRequest inValue = new SimplifikasiFID.ServiceDOC.GetFileIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileIdRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.GetFileData2Response SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileData2(SimplifikasiFID.ServiceDOC.GetFileData2Request request) {
            return base.Channel.GetFileData2(request);
        }
        
        public byte[] GetFileData2(string source, string key1, string key2, int key3, int key4, int revision, out string contentType) {
            SimplifikasiFID.ServiceDOC.GetFileData2Request inValue = new SimplifikasiFID.ServiceDOC.GetFileData2Request();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileData2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            SimplifikasiFID.ServiceDOC.GetFileData2Response retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileData2(inValue);
            contentType = retVal.Body.contentType;
            return retVal.Body.GetFileData2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileData2Response> SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileData2Async(SimplifikasiFID.ServiceDOC.GetFileData2Request request) {
            return base.Channel.GetFileData2Async(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileData2Response> GetFileData2Async(string source, string key1, string key2, int key3, int key4, int revision) {
            SimplifikasiFID.ServiceDOC.GetFileData2Request inValue = new SimplifikasiFID.ServiceDOC.GetFileData2Request();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileData2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileData2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.GetFileDataResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileData(SimplifikasiFID.ServiceDOC.GetFileDataRequest request) {
            return base.Channel.GetFileData(request);
        }
        
        public byte[] GetFileData(string source, string key1, string key2, int key3, int key4, int revision) {
            SimplifikasiFID.ServiceDOC.GetFileDataRequest inValue = new SimplifikasiFID.ServiceDOC.GetFileDataRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileDataRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            SimplifikasiFID.ServiceDOC.GetFileDataResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileData(inValue);
            return retVal.Body.GetFileDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileDataResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileDataAsync(SimplifikasiFID.ServiceDOC.GetFileDataRequest request) {
            return base.Channel.GetFileDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileDataResponse> GetFileDataAsync(string source, string key1, string key2, int key3, int key4, int revision) {
            SimplifikasiFID.ServiceDOC.GetFileDataRequest inValue = new SimplifikasiFID.ServiceDOC.GetFileDataRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileDataRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.GetFileDataByIdResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileDataById(SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest request) {
            return base.Channel.GetFileDataById(request);
        }
        
        public byte[] GetFileDataById(int Id, string username, string password) {
            SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest inValue = new SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileDataByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            SimplifikasiFID.ServiceDOC.GetFileDataByIdResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileDataById(inValue);
            return retVal.Body.GetFileDataByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileDataByIdResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetFileDataByIdAsync(SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest request) {
            return base.Channel.GetFileDataByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetFileDataByIdResponse> GetFileDataByIdAsync(int Id, string username, string password) {
            SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest inValue = new SimplifikasiFID.ServiceDOC.GetFileDataByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetFileDataByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetFileDataByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.DeleteFileResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.DeleteFile(SimplifikasiFID.ServiceDOC.DeleteFileRequest request) {
            return base.Channel.DeleteFile(request);
        }
        
        public string DeleteFile(string source, string key1, string key2, int key3, int key4, int revision, string delUser) {
            SimplifikasiFID.ServiceDOC.DeleteFileRequest inValue = new SimplifikasiFID.ServiceDOC.DeleteFileRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.DeleteFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            inValue.Body.delUser = delUser;
            SimplifikasiFID.ServiceDOC.DeleteFileResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).DeleteFile(inValue);
            return retVal.Body.DeleteFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFileResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.DeleteFileAsync(SimplifikasiFID.ServiceDOC.DeleteFileRequest request) {
            return base.Channel.DeleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFileResponse> DeleteFileAsync(string source, string key1, string key2, int key3, int key4, int revision, string delUser) {
            SimplifikasiFID.ServiceDOC.DeleteFileRequest inValue = new SimplifikasiFID.ServiceDOC.DeleteFileRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.DeleteFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            inValue.Body.delUser = delUser;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).DeleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.DeleteFileByIdResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.DeleteFileById(SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest request) {
            return base.Channel.DeleteFileById(request);
        }
        
        public string DeleteFileById(int Id, string username, string password, string delUser) {
            SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest inValue = new SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.DeleteFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            SimplifikasiFID.ServiceDOC.DeleteFileByIdResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).DeleteFileById(inValue);
            return retVal.Body.DeleteFileByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFileByIdResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.DeleteFileByIdAsync(SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest request) {
            return base.Channel.DeleteFileByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFileByIdResponse> DeleteFileByIdAsync(int Id, string username, string password, string delUser) {
            SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest inValue = new SimplifikasiFID.ServiceDOC.DeleteFileByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.DeleteFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).DeleteFileByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.DeleteFilePreById(SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest request) {
            return base.Channel.DeleteFilePreById(request);
        }
        
        public string DeleteFilePreById(int Id, string username, string password, string delUser) {
            SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest inValue = new SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).DeleteFilePreById(inValue);
            return retVal.Body.DeleteFilePreByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.DeleteFilePreByIdAsync(SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest request) {
            return base.Channel.DeleteFilePreByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.DeleteFilePreByIdResponse> DeleteFilePreByIdAsync(int Id, string username, string password, string delUser) {
            SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest inValue = new SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.DeleteFilePreByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).DeleteFilePreByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.MoveFileByIdResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.MoveFileById(SimplifikasiFID.ServiceDOC.MoveFileByIdRequest request) {
            return base.Channel.MoveFileById(request);
        }
        
        public string MoveFileById(int Id, string username, string password, string delUser, string OldKey2) {
            SimplifikasiFID.ServiceDOC.MoveFileByIdRequest inValue = new SimplifikasiFID.ServiceDOC.MoveFileByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.MoveFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            inValue.Body.OldKey2 = OldKey2;
            SimplifikasiFID.ServiceDOC.MoveFileByIdResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).MoveFileById(inValue);
            return retVal.Body.MoveFileByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.MoveFileByIdResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.MoveFileByIdAsync(SimplifikasiFID.ServiceDOC.MoveFileByIdRequest request) {
            return base.Channel.MoveFileByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.MoveFileByIdResponse> MoveFileByIdAsync(int Id, string username, string password, string delUser, string OldKey2) {
            SimplifikasiFID.ServiceDOC.MoveFileByIdRequest inValue = new SimplifikasiFID.ServiceDOC.MoveFileByIdRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.MoveFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            inValue.Body.OldKey2 = OldKey2;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).MoveFileByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.GetMergePdfFileResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetMergePdfFile(SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest request) {
            return base.Channel.GetMergePdfFile(request);
        }
        
        public byte[] GetMergePdfFile(string JsonID, string username, string password) {
            SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest inValue = new SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetMergePdfFileRequestBody();
            inValue.Body.JsonID = JsonID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            SimplifikasiFID.ServiceDOC.GetMergePdfFileResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetMergePdfFile(inValue);
            return retVal.Body.GetMergePdfFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetMergePdfFileResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.GetMergePdfFileAsync(SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest request) {
            return base.Channel.GetMergePdfFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.GetMergePdfFileResponse> GetMergePdfFileAsync(string JsonID, string username, string password) {
            SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest inValue = new SimplifikasiFID.ServiceDOC.GetMergePdfFileRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.GetMergePdfFileRequestBody();
            inValue.Body.JsonID = JsonID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).GetMergePdfFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimplifikasiFID.ServiceDOC.OrganizeResponse SimplifikasiFID.ServiceDOC.ServiceDocSoap.Organize(SimplifikasiFID.ServiceDOC.OrganizeRequest request) {
            return base.Channel.Organize(request);
        }
        
        public int Organize(string source) {
            SimplifikasiFID.ServiceDOC.OrganizeRequest inValue = new SimplifikasiFID.ServiceDOC.OrganizeRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.OrganizeRequestBody();
            inValue.Body.source = source;
            SimplifikasiFID.ServiceDOC.OrganizeResponse retVal = ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).Organize(inValue);
            return retVal.Body.OrganizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.OrganizeResponse> SimplifikasiFID.ServiceDOC.ServiceDocSoap.OrganizeAsync(SimplifikasiFID.ServiceDOC.OrganizeRequest request) {
            return base.Channel.OrganizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimplifikasiFID.ServiceDOC.OrganizeResponse> OrganizeAsync(string source) {
            SimplifikasiFID.ServiceDOC.OrganizeRequest inValue = new SimplifikasiFID.ServiceDOC.OrganizeRequest();
            inValue.Body = new SimplifikasiFID.ServiceDOC.OrganizeRequestBody();
            inValue.Body.source = source;
            return ((SimplifikasiFID.ServiceDOC.ServiceDocSoap)(this)).OrganizeAsync(inValue);
        }
    }
}
