//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDOC
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDOC.ServiceDocSoap")]
    public interface ServiceDocSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile3", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.PutFile3Response> PutFile3Async(ServiceDOC.PutFile3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.PutFile2Response> PutFile2Async(ServiceDOC.PutFile2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.PutFileResponse> PutFileAsync(ServiceDOC.PutFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileId", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.GetFileIdResponse> GetFileIdAsync(ServiceDOC.GetFileIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.GetFileData2Response> GetFileData2Async(ServiceDOC.GetFileData2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileData", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.GetFileDataResponse> GetFileDataAsync(ServiceDOC.GetFileDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileDataById", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.GetFileDataByIdResponse> GetFileDataByIdAsync(ServiceDOC.GetFileDataByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.DeleteFileResponse> DeleteFileAsync(ServiceDOC.DeleteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFileById", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.DeleteFileByIdResponse> DeleteFileByIdAsync(ServiceDOC.DeleteFileByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFilePreById", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.DeleteFilePreByIdResponse> DeleteFilePreByIdAsync(ServiceDOC.DeleteFilePreByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MoveFileById", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.MoveFileByIdResponse> MoveFileByIdAsync(ServiceDOC.MoveFileByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMergePdfFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.GetMergePdfFileResponse> GetMergePdfFileAsync(ServiceDOC.GetMergePdfFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Organize", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDOC.OrganizeResponse> OrganizeAsync(ServiceDOC.OrganizeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile3", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.PutFile3RequestBody Body;
        
        public PutFile3Request()
        {
        }
        
        public PutFile3Request(ServiceDOC.PutFile3RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile3RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrgFileName;
        
        public PutFile3RequestBody()
        {
        }
        
        public PutFile3RequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName)
        {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
            this.OrgFileName = OrgFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile3Response", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.PutFile3ResponseBody Body;
        
        public PutFile3Response()
        {
        }
        
        public PutFile3Response(ServiceDOC.PutFile3ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile3ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFile3Result;
        
        public PutFile3ResponseBody()
        {
        }
        
        public PutFile3ResponseBody(string PutFile3Result)
        {
            this.PutFile3Result = PutFile3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile2", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.PutFile2RequestBody Body;
        
        public PutFile2Request()
        {
        }
        
        public PutFile2Request(ServiceDOC.PutFile2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string OrgFileName;
        
        public PutFile2RequestBody()
        {
        }
        
        public PutFile2RequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName)
        {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
            this.OrgFileName = OrgFileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFile2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile2Response", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.PutFile2ResponseBody Body;
        
        public PutFile2Response()
        {
        }
        
        public PutFile2Response(ServiceDOC.PutFile2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFile2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFile2Result;
        
        public PutFile2ResponseBody()
        {
        }
        
        public PutFile2ResponseBody(string PutFile2Result)
        {
            this.PutFile2Result = PutFile2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFile", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.PutFileRequestBody Body;
        
        public PutFileRequest()
        {
        }
        
        public PutFileRequest(ServiceDOC.PutFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string catId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string contentType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string entryUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] data;
        
        public PutFileRequestBody()
        {
        }
        
        public PutFileRequestBody(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data)
        {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.catId = catId;
            this.revision = revision;
            this.fileName = fileName;
            this.contentType = contentType;
            this.remark = remark;
            this.entryUser = entryUser;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.PutFileResponseBody Body;
        
        public PutFileResponse()
        {
        }
        
        public PutFileResponse(ServiceDOC.PutFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PutFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PutFileResult;
        
        public PutFileResponseBody()
        {
        }
        
        public PutFileResponseBody(string PutFileResult)
        {
            this.PutFileResult = PutFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileId", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileIdRequestBody Body;
        
        public GetFileIdRequest()
        {
        }
        
        public GetFileIdRequest(ServiceDOC.GetFileIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileIdRequestBody()
        {
        }
        
        public GetFileIdRequestBody(string source, string key1, string key2, int key3, int key4, int revision)
        {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileIdResponseBody Body;
        
        public GetFileIdResponse()
        {
        }
        
        public GetFileIdResponse(ServiceDOC.GetFileIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetFileIdResult;
        
        public GetFileIdResponseBody()
        {
        }
        
        public GetFileIdResponseBody(int GetFileIdResult)
        {
            this.GetFileIdResult = GetFileIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileData2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData2", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileData2RequestBody Body;
        
        public GetFileData2Request()
        {
        }
        
        public GetFileData2Request(ServiceDOC.GetFileData2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileData2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileData2RequestBody()
        {
        }
        
        public GetFileData2RequestBody(string source, string key1, string key2, int key3, int key4, int revision)
        {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileData2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData2Response", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileData2ResponseBody Body;
        
        public GetFileData2Response()
        {
        }
        
        public GetFileData2Response(ServiceDOC.GetFileData2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileData2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileData2Result;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contentType;
        
        public GetFileData2ResponseBody()
        {
        }
        
        public GetFileData2ResponseBody(byte[] GetFileData2Result, string contentType)
        {
            this.GetFileData2Result = GetFileData2Result;
            this.contentType = contentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileData", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileDataRequestBody Body;
        
        public GetFileDataRequest()
        {
        }
        
        public GetFileDataRequest(ServiceDOC.GetFileDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        public GetFileDataRequestBody()
        {
        }
        
        public GetFileDataRequestBody(string source, string key1, string key2, int key3, int key4, int revision)
        {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileDataResponseBody Body;
        
        public GetFileDataResponse()
        {
        }
        
        public GetFileDataResponse(ServiceDOC.GetFileDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileDataResult;
        
        public GetFileDataResponseBody()
        {
        }
        
        public GetFileDataResponseBody(byte[] GetFileDataResult)
        {
            this.GetFileDataResult = GetFileDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataById", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileDataByIdRequestBody Body;
        
        public GetFileDataByIdRequest()
        {
        }
        
        public GetFileDataByIdRequest(ServiceDOC.GetFileDataByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetFileDataByIdRequestBody()
        {
        }
        
        public GetFileDataByIdRequestBody(int Id, string username, string password)
        {
            this.Id = Id;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDataByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDataByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetFileDataByIdResponseBody Body;
        
        public GetFileDataByIdResponse()
        {
        }
        
        public GetFileDataByIdResponse(ServiceDOC.GetFileDataByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDataByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileDataByIdResult;
        
        public GetFileDataByIdResponseBody()
        {
        }
        
        public GetFileDataByIdResponseBody(byte[] GetFileDataByIdResult)
        {
            this.GetFileDataByIdResult = GetFileDataByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFile", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.DeleteFileRequestBody Body;
        
        public DeleteFileRequest()
        {
        }
        
        public DeleteFileRequest(ServiceDOC.DeleteFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string key2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int key3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int key4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int revision;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string delUser;
        
        public DeleteFileRequestBody()
        {
        }
        
        public DeleteFileRequestBody(string source, string key1, string key2, int key3, int key4, int revision, string delUser)
        {
            this.source = source;
            this.key1 = key1;
            this.key2 = key2;
            this.key3 = key3;
            this.key4 = key4;
            this.revision = revision;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.DeleteFileResponseBody Body;
        
        public DeleteFileResponse()
        {
        }
        
        public DeleteFileResponse(ServiceDOC.DeleteFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileResult;
        
        public DeleteFileResponseBody()
        {
        }
        
        public DeleteFileResponseBody(string DeleteFileResult)
        {
            this.DeleteFileResult = DeleteFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileById", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.DeleteFileByIdRequestBody Body;
        
        public DeleteFileByIdRequest()
        {
        }
        
        public DeleteFileByIdRequest(ServiceDOC.DeleteFileByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        public DeleteFileByIdRequestBody()
        {
        }
        
        public DeleteFileByIdRequestBody(int Id, string username, string password, string delUser)
        {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFileByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFileByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.DeleteFileByIdResponseBody Body;
        
        public DeleteFileByIdResponse()
        {
        }
        
        public DeleteFileByIdResponse(ServiceDOC.DeleteFileByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFileByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFileByIdResult;
        
        public DeleteFileByIdResponseBody()
        {
        }
        
        public DeleteFileByIdResponseBody(string DeleteFileByIdResult)
        {
            this.DeleteFileByIdResult = DeleteFileByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilePreByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilePreById", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.DeleteFilePreByIdRequestBody Body;
        
        public DeleteFilePreByIdRequest()
        {
        }
        
        public DeleteFilePreByIdRequest(ServiceDOC.DeleteFilePreByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilePreByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        public DeleteFilePreByIdRequestBody()
        {
        }
        
        public DeleteFilePreByIdRequestBody(int Id, string username, string password, string delUser)
        {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilePreByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilePreByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.DeleteFilePreByIdResponseBody Body;
        
        public DeleteFilePreByIdResponse()
        {
        }
        
        public DeleteFilePreByIdResponse(ServiceDOC.DeleteFilePreByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilePreByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFilePreByIdResult;
        
        public DeleteFilePreByIdResponseBody()
        {
        }
        
        public DeleteFilePreByIdResponseBody(string DeleteFilePreByIdResult)
        {
            this.DeleteFilePreByIdResult = DeleteFilePreByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveFileByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveFileById", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.MoveFileByIdRequestBody Body;
        
        public MoveFileByIdRequest()
        {
        }
        
        public MoveFileByIdRequest(ServiceDOC.MoveFileByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveFileByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string delUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OldKey2;
        
        public MoveFileByIdRequestBody()
        {
        }
        
        public MoveFileByIdRequestBody(int Id, string username, string password, string delUser, string OldKey2)
        {
            this.Id = Id;
            this.username = username;
            this.password = password;
            this.delUser = delUser;
            this.OldKey2 = OldKey2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MoveFileByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MoveFileByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.MoveFileByIdResponseBody Body;
        
        public MoveFileByIdResponse()
        {
        }
        
        public MoveFileByIdResponse(ServiceDOC.MoveFileByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MoveFileByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MoveFileByIdResult;
        
        public MoveFileByIdResponseBody()
        {
        }
        
        public MoveFileByIdResponseBody(string MoveFileByIdResult)
        {
            this.MoveFileByIdResult = MoveFileByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMergePdfFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMergePdfFile", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetMergePdfFileRequestBody Body;
        
        public GetMergePdfFileRequest()
        {
        }
        
        public GetMergePdfFileRequest(ServiceDOC.GetMergePdfFileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMergePdfFileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JsonID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public GetMergePdfFileRequestBody()
        {
        }
        
        public GetMergePdfFileRequestBody(string JsonID, string username, string password)
        {
            this.JsonID = JsonID;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMergePdfFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMergePdfFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.GetMergePdfFileResponseBody Body;
        
        public GetMergePdfFileResponse()
        {
        }
        
        public GetMergePdfFileResponse(ServiceDOC.GetMergePdfFileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMergePdfFileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetMergePdfFileResult;
        
        public GetMergePdfFileResponseBody()
        {
        }
        
        public GetMergePdfFileResponseBody(byte[] GetMergePdfFileResult)
        {
            this.GetMergePdfFileResult = GetMergePdfFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Organize", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.OrganizeRequestBody Body;
        
        public OrganizeRequest()
        {
        }
        
        public OrganizeRequest(ServiceDOC.OrganizeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        public OrganizeRequestBody()
        {
        }
        
        public OrganizeRequestBody(string source)
        {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrganizeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrganizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceDOC.OrganizeResponseBody Body;
        
        public OrganizeResponse()
        {
        }
        
        public OrganizeResponse(ServiceDOC.OrganizeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OrganizeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int OrganizeResult;
        
        public OrganizeResponseBody()
        {
        }
        
        public OrganizeResponseBody(int OrganizeResult)
        {
            this.OrganizeResult = OrganizeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceDocSoapChannel : ServiceDOC.ServiceDocSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceDocSoapClient : System.ServiceModel.ClientBase<ServiceDOC.ServiceDocSoap>, ServiceDOC.ServiceDocSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceDocSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceDocSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceDocSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceDocSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceDocSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceDocSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceDocSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceDocSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.PutFile3Response> ServiceDOC.ServiceDocSoap.PutFile3Async(ServiceDOC.PutFile3Request request)
        {
            return base.Channel.PutFile3Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.PutFile3Response> PutFile3Async(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName)
        {
            ServiceDOC.PutFile3Request inValue = new ServiceDOC.PutFile3Request();
            inValue.Body = new ServiceDOC.PutFile3RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            return ((ServiceDOC.ServiceDocSoap)(this)).PutFile3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.PutFile2Response> ServiceDOC.ServiceDocSoap.PutFile2Async(ServiceDOC.PutFile2Request request)
        {
            return base.Channel.PutFile2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.PutFile2Response> PutFile2Async(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data, string OrgFileName)
        {
            ServiceDOC.PutFile2Request inValue = new ServiceDOC.PutFile2Request();
            inValue.Body = new ServiceDOC.PutFile2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            inValue.Body.OrgFileName = OrgFileName;
            return ((ServiceDOC.ServiceDocSoap)(this)).PutFile2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.PutFileResponse> ServiceDOC.ServiceDocSoap.PutFileAsync(ServiceDOC.PutFileRequest request)
        {
            return base.Channel.PutFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.PutFileResponse> PutFileAsync(string source, string key1, string key2, int key3, int key4, string catId, int revision, string fileName, string contentType, string remark, string entryUser, byte[] data)
        {
            ServiceDOC.PutFileRequest inValue = new ServiceDOC.PutFileRequest();
            inValue.Body = new ServiceDOC.PutFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.catId = catId;
            inValue.Body.revision = revision;
            inValue.Body.fileName = fileName;
            inValue.Body.contentType = contentType;
            inValue.Body.remark = remark;
            inValue.Body.entryUser = entryUser;
            inValue.Body.data = data;
            return ((ServiceDOC.ServiceDocSoap)(this)).PutFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.GetFileIdResponse> ServiceDOC.ServiceDocSoap.GetFileIdAsync(ServiceDOC.GetFileIdRequest request)
        {
            return base.Channel.GetFileIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.GetFileIdResponse> GetFileIdAsync(string source, string key1, string key2, int key3, int key4, int revision)
        {
            ServiceDOC.GetFileIdRequest inValue = new ServiceDOC.GetFileIdRequest();
            inValue.Body = new ServiceDOC.GetFileIdRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((ServiceDOC.ServiceDocSoap)(this)).GetFileIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.GetFileData2Response> ServiceDOC.ServiceDocSoap.GetFileData2Async(ServiceDOC.GetFileData2Request request)
        {
            return base.Channel.GetFileData2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.GetFileData2Response> GetFileData2Async(string source, string key1, string key2, int key3, int key4, int revision)
        {
            ServiceDOC.GetFileData2Request inValue = new ServiceDOC.GetFileData2Request();
            inValue.Body = new ServiceDOC.GetFileData2RequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((ServiceDOC.ServiceDocSoap)(this)).GetFileData2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.GetFileDataResponse> ServiceDOC.ServiceDocSoap.GetFileDataAsync(ServiceDOC.GetFileDataRequest request)
        {
            return base.Channel.GetFileDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.GetFileDataResponse> GetFileDataAsync(string source, string key1, string key2, int key3, int key4, int revision)
        {
            ServiceDOC.GetFileDataRequest inValue = new ServiceDOC.GetFileDataRequest();
            inValue.Body = new ServiceDOC.GetFileDataRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            return ((ServiceDOC.ServiceDocSoap)(this)).GetFileDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.GetFileDataByIdResponse> ServiceDOC.ServiceDocSoap.GetFileDataByIdAsync(ServiceDOC.GetFileDataByIdRequest request)
        {
            return base.Channel.GetFileDataByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.GetFileDataByIdResponse> GetFileDataByIdAsync(int Id, string username, string password)
        {
            ServiceDOC.GetFileDataByIdRequest inValue = new ServiceDOC.GetFileDataByIdRequest();
            inValue.Body = new ServiceDOC.GetFileDataByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceDOC.ServiceDocSoap)(this)).GetFileDataByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.DeleteFileResponse> ServiceDOC.ServiceDocSoap.DeleteFileAsync(ServiceDOC.DeleteFileRequest request)
        {
            return base.Channel.DeleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.DeleteFileResponse> DeleteFileAsync(string source, string key1, string key2, int key3, int key4, int revision, string delUser)
        {
            ServiceDOC.DeleteFileRequest inValue = new ServiceDOC.DeleteFileRequest();
            inValue.Body = new ServiceDOC.DeleteFileRequestBody();
            inValue.Body.source = source;
            inValue.Body.key1 = key1;
            inValue.Body.key2 = key2;
            inValue.Body.key3 = key3;
            inValue.Body.key4 = key4;
            inValue.Body.revision = revision;
            inValue.Body.delUser = delUser;
            return ((ServiceDOC.ServiceDocSoap)(this)).DeleteFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.DeleteFileByIdResponse> ServiceDOC.ServiceDocSoap.DeleteFileByIdAsync(ServiceDOC.DeleteFileByIdRequest request)
        {
            return base.Channel.DeleteFileByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.DeleteFileByIdResponse> DeleteFileByIdAsync(int Id, string username, string password, string delUser)
        {
            ServiceDOC.DeleteFileByIdRequest inValue = new ServiceDOC.DeleteFileByIdRequest();
            inValue.Body = new ServiceDOC.DeleteFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            return ((ServiceDOC.ServiceDocSoap)(this)).DeleteFileByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.DeleteFilePreByIdResponse> ServiceDOC.ServiceDocSoap.DeleteFilePreByIdAsync(ServiceDOC.DeleteFilePreByIdRequest request)
        {
            return base.Channel.DeleteFilePreByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.DeleteFilePreByIdResponse> DeleteFilePreByIdAsync(int Id, string username, string password, string delUser)
        {
            ServiceDOC.DeleteFilePreByIdRequest inValue = new ServiceDOC.DeleteFilePreByIdRequest();
            inValue.Body = new ServiceDOC.DeleteFilePreByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            return ((ServiceDOC.ServiceDocSoap)(this)).DeleteFilePreByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.MoveFileByIdResponse> ServiceDOC.ServiceDocSoap.MoveFileByIdAsync(ServiceDOC.MoveFileByIdRequest request)
        {
            return base.Channel.MoveFileByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.MoveFileByIdResponse> MoveFileByIdAsync(int Id, string username, string password, string delUser, string OldKey2)
        {
            ServiceDOC.MoveFileByIdRequest inValue = new ServiceDOC.MoveFileByIdRequest();
            inValue.Body = new ServiceDOC.MoveFileByIdRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.delUser = delUser;
            inValue.Body.OldKey2 = OldKey2;
            return ((ServiceDOC.ServiceDocSoap)(this)).MoveFileByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.GetMergePdfFileResponse> ServiceDOC.ServiceDocSoap.GetMergePdfFileAsync(ServiceDOC.GetMergePdfFileRequest request)
        {
            return base.Channel.GetMergePdfFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.GetMergePdfFileResponse> GetMergePdfFileAsync(string JsonID, string username, string password)
        {
            ServiceDOC.GetMergePdfFileRequest inValue = new ServiceDOC.GetMergePdfFileRequest();
            inValue.Body = new ServiceDOC.GetMergePdfFileRequestBody();
            inValue.Body.JsonID = JsonID;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceDOC.ServiceDocSoap)(this)).GetMergePdfFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDOC.OrganizeResponse> ServiceDOC.ServiceDocSoap.OrganizeAsync(ServiceDOC.OrganizeRequest request)
        {
            return base.Channel.OrganizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDOC.OrganizeResponse> OrganizeAsync(string source)
        {
            ServiceDOC.OrganizeRequest inValue = new ServiceDOC.OrganizeRequest();
            inValue.Body = new ServiceDOC.OrganizeRequestBody();
            inValue.Body.source = source;
            return ((ServiceDOC.ServiceDocSoap)(this)).OrganizeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceDocSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceDocSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceDocSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ptprkpnas02:8027/ServiceDoc.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceDocSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ptprkpnas02:8027/ServiceDoc.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceDocSoap,
            
            ServiceDocSoap12,
        }
    }
}
