//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifikasiFID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_GateReview
    {
        public int ID { get; set; }
        public string Jabatan { get; set; }
        public string Fungsi { get; set; }
    }
}
