//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifikasiFID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Status
    {
        public int statusID { get; set; }
        public Nullable<short> status { get; set; }
        public string value { get; set; }
        public string SlaDefault { get; set; }
    }
}
