//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifikasiFID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TemplateForm
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string HtmlTag { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
    }
}
