//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifikasiFID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_UploadFiles
    {
        public int UploadID { get; set; }
        public string NoFID { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
        public string Key4 { get; set; }
        public string UploadBy { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public Nullable<short> Status { get; set; }
        public string Category { get; set; }
        public string HtmlTag { get; set; }
        public Nullable<bool> StatusSign { get; set; }
    }
}
