//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifikasiFID.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimplyFIDEntities : DbContext
    {
        public SimplyFIDEntities()
            : base("name=SimplyFIDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Email> M_Email { get; set; }
        public virtual DbSet<M_EmailManager> M_EmailManager { get; set; }
        public virtual DbSet<M_Fungsi> M_Fungsi { get; set; }
        public virtual DbSet<M_Status> M_Status { get; set; }
        public virtual DbSet<M_TemplateForm> M_TemplateForm { get; set; }
        public virtual DbSet<M_UploadFiles> M_UploadFiles { get; set; }
        public virtual DbSet<M_User> M_User { get; set; }
        public virtual DbSet<T_Catatan> T_Catatan { get; set; }
        public virtual DbSet<T_FID> T_FID { get; set; }
        public virtual DbSet<V_FID> V_FID { get; set; }
        public virtual DbSet<M_GateReview> M_GateReview { get; set; }
    }
}
