//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplifikasiFID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FID
    {
        public int DocID { get; set; }
        public string NoFID { get; set; }
        public string Judulfid { get; set; }
        public string TahunAnggaran { get; set; }
        public Nullable<decimal> NilaiABI { get; set; }
        public string Jenisfid { get; set; }
        public string Fungsipengusul { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
