//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSSO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateResult", Namespace="SSO")]
    public partial class ValidateResult : object
    {
        
        private bool ValidateUserResultField;
        
        private string NIPField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ValidateUserResult
        {
            get
            {
                return this.ValidateUserResultField;
            }
            set
            {
                this.ValidateUserResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NIP
        {
            get
            {
                return this.NIPField;
            }
            set
            {
                this.NIPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="SSO", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SSO", ConfigurationName="ServiceSSO.SSOWSSoap")]
    public interface SSOWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.ValidateUserResponse> ValidateUserAsync(ServiceSSO.ValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUser_2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.ValidateUser_2Response> ValidateUser_2Async(ServiceSSO.ValidateUser_2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUserGetNIP", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.ValidateUserGetNIPResponse> ValidateUserGetNIPAsync(ServiceSSO.ValidateUserGetNIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/CreateToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.CreateTokenResponse> CreateTokenAsync(ServiceSSO.CreateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/Verify", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.VerifyResponse> VerifyAsync(ServiceSSO.VerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetUserUnitResponse> GetUserUnitAsync(ServiceSSO.GetUserUnitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetAllRolesResponse> GetAllRolesAsync(ServiceSSO.GetAllRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetRolesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetRolesForUserResponse> GetRolesForUserAsync(ServiceSSO.GetRolesForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUsersInRole", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetUsersInRoleResponse> GetUsersInRoleAsync(ServiceSSO.GetUsersInRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/IsUserInRole", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.IsUserInRoleResponse> IsUserInRoleAsync(ServiceSSO.IsUserInRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/RoleExists", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.RoleExistsResponse> RoleExistsAsync(ServiceSSO.RoleExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/DeleteToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.DeleteTokenResponse> DeleteTokenAsync(ServiceSSO.DeleteTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccessForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetAccessForUserResponse> GetAccessForUserAsync(ServiceSSO.GetAccessForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.ChangePasswordResponse> ChangePasswordAsync(ServiceSSO.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserType", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetUserTypeResponse> GetUserTypeAsync(ServiceSSO.GetUserTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllowModul", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetAllowModulResponse> GetAllowModulAsync(ServiceSSO.GetAllowModulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccesExtend", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetAccesExtendResponse> GetAccesExtendAsync(ServiceSSO.GetAccesExtendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/CheckAccGroupUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.CheckAccGroupUserResponse> CheckAccGroupUserAsync(ServiceSSO.CheckAccGroupUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnitV2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceSSO.GetUserUnitV2Response> GetUserUnitV2Async(ServiceSSO.GetUserUnitV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser", Namespace="SSO", Order=0)]
        public ServiceSSO.ValidateUserRequestBody Body;
        
        public ValidateUserRequest()
        {
        }
        
        public ValidateUserRequest(ServiceSSO.ValidateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserRequestBody()
        {
        }
        
        public ValidateUserRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.ValidateUserResponseBody Body;
        
        public ValidateUserResponse()
        {
        }
        
        public ValidateUserResponse(ServiceSSO.ValidateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponseBody()
        {
        }
        
        public ValidateUserResponseBody(bool ValidateUserResult)
        {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUser_2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser_2", Namespace="SSO", Order=0)]
        public ServiceSSO.ValidateUser_2RequestBody Body;
        
        public ValidateUser_2Request()
        {
        }
        
        public ValidateUser_2Request(ServiceSSO.ValidateUser_2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUser_2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUser_2RequestBody()
        {
        }
        
        public ValidateUser_2RequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUser_2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser_2Response", Namespace="SSO", Order=0)]
        public ServiceSSO.ValidateUser_2ResponseBody Body;
        
        public ValidateUser_2Response()
        {
        }
        
        public ValidateUser_2Response(ServiceSSO.ValidateUser_2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUser_2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateUser_2Result;
        
        public ValidateUser_2ResponseBody()
        {
        }
        
        public ValidateUser_2ResponseBody(bool ValidateUser_2Result)
        {
            this.ValidateUser_2Result = ValidateUser_2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserGetNIPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserGetNIP", Namespace="SSO", Order=0)]
        public ServiceSSO.ValidateUserGetNIPRequestBody Body;
        
        public ValidateUserGetNIPRequest()
        {
        }
        
        public ValidateUserGetNIPRequest(ServiceSSO.ValidateUserGetNIPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserGetNIPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserGetNIPRequestBody()
        {
        }
        
        public ValidateUserGetNIPRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserGetNIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserGetNIPResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.ValidateUserGetNIPResponseBody Body;
        
        public ValidateUserGetNIPResponse()
        {
        }
        
        public ValidateUserGetNIPResponse(ServiceSSO.ValidateUserGetNIPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserGetNIPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSSO.ValidateResult ValidateUserGetNIPResult;
        
        public ValidateUserGetNIPResponseBody()
        {
        }
        
        public ValidateUserGetNIPResponseBody(ServiceSSO.ValidateResult ValidateUserGetNIPResult)
        {
            this.ValidateUserGetNIPResult = ValidateUserGetNIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateToken", Namespace="SSO", Order=0)]
        public ServiceSSO.CreateTokenRequestBody Body;
        
        public CreateTokenRequest()
        {
        }
        
        public CreateTokenRequest(ServiceSSO.CreateTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CreateTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public CreateTokenRequestBody()
        {
        }
        
        public CreateTokenRequestBody(string username, string token)
        {
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTokenResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.CreateTokenResponseBody Body;
        
        public CreateTokenResponse()
        {
        }
        
        public CreateTokenResponse(ServiceSSO.CreateTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CreateTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateTokenResult;
        
        public CreateTokenResponseBody()
        {
        }
        
        public CreateTokenResponseBody(bool CreateTokenResult)
        {
            this.CreateTokenResult = CreateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify", Namespace="SSO", Order=0)]
        public ServiceSSO.VerifyRequestBody Body;
        
        public VerifyRequest()
        {
        }
        
        public VerifyRequest(ServiceSSO.VerifyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class VerifyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public VerifyRequestBody()
        {
        }
        
        public VerifyRequestBody(string username, string token)
        {
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.VerifyResponseBody Body;
        
        public VerifyResponse()
        {
        }
        
        public VerifyResponse(ServiceSSO.VerifyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class VerifyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyResult;
        
        public VerifyResponseBody()
        {
        }
        
        public VerifyResponseBody(bool VerifyResult)
        {
            this.VerifyResult = VerifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnit", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUserUnitRequestBody Body;
        
        public GetUserUnitRequest()
        {
        }
        
        public GetUserUnitRequest(ServiceSSO.GetUserUnitRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserUnitRequestBody()
        {
        }
        
        public GetUserUnitRequestBody(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUserUnitResponseBody Body;
        
        public GetUserUnitResponse()
        {
        }
        
        public GetUserUnitResponse(ServiceSSO.GetUserUnitResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserUnitResult;
        
        public GetUserUnitResponseBody()
        {
        }
        
        public GetUserUnitResponseBody(string GetUserUnitResult)
        {
            this.GetUserUnitResult = GetUserUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoles", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAllRolesRequestBody Body;
        
        public GetAllRolesRequest()
        {
        }
        
        public GetAllRolesRequest(ServiceSSO.GetAllRolesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllRolesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public GetAllRolesRequestBody()
        {
        }
        
        public GetAllRolesRequestBody(string appName)
        {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRolesResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAllRolesResponseBody Body;
        
        public GetAllRolesResponse()
        {
        }
        
        public GetAllRolesResponse(ServiceSSO.GetAllRolesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllRolesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSSO.ArrayOfString GetAllRolesResult;
        
        public GetAllRolesResponseBody()
        {
        }
        
        public GetAllRolesResponseBody(ServiceSSO.ArrayOfString GetAllRolesResult)
        {
            this.GetAllRolesResult = GetAllRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUser", Namespace="SSO", Order=0)]
        public ServiceSSO.GetRolesForUserRequestBody Body;
        
        public GetRolesForUserRequest()
        {
        }
        
        public GetRolesForUserRequest(ServiceSSO.GetRolesForUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetRolesForUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        public GetRolesForUserRequestBody()
        {
        }
        
        public GetRolesForUserRequestBody(string username, string appName)
        {
            this.username = username;
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUserResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetRolesForUserResponseBody Body;
        
        public GetRolesForUserResponse()
        {
        }
        
        public GetRolesForUserResponse(ServiceSSO.GetRolesForUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetRolesForUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSSO.ArrayOfString GetRolesForUserResult;
        
        public GetRolesForUserResponseBody()
        {
        }
        
        public GetRolesForUserResponseBody(ServiceSSO.ArrayOfString GetRolesForUserResult)
        {
            this.GetRolesForUserResult = GetRolesForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersInRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersInRole", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUsersInRoleRequestBody Body;
        
        public GetUsersInRoleRequest()
        {
        }
        
        public GetUsersInRoleRequest(ServiceSSO.GetUsersInRoleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUsersInRoleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleName;
        
        public GetUsersInRoleRequestBody()
        {
        }
        
        public GetUsersInRoleRequestBody(string appName, string roleName)
        {
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersInRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersInRoleResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUsersInRoleResponseBody Body;
        
        public GetUsersInRoleResponse()
        {
        }
        
        public GetUsersInRoleResponse(ServiceSSO.GetUsersInRoleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUsersInRoleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceSSO.ArrayOfString GetUsersInRoleResult;
        
        public GetUsersInRoleResponseBody()
        {
        }
        
        public GetUsersInRoleResponseBody(ServiceSSO.ArrayOfString GetUsersInRoleResult)
        {
            this.GetUsersInRoleResult = GetUsersInRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserInRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserInRole", Namespace="SSO", Order=0)]
        public ServiceSSO.IsUserInRoleRequestBody Body;
        
        public IsUserInRoleRequest()
        {
        }
        
        public IsUserInRoleRequest(ServiceSSO.IsUserInRoleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class IsUserInRoleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roleName;
        
        public IsUserInRoleRequestBody()
        {
        }
        
        public IsUserInRoleRequestBody(string username, string appName, string roleName)
        {
            this.username = username;
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserInRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserInRoleResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.IsUserInRoleResponseBody Body;
        
        public IsUserInRoleResponse()
        {
        }
        
        public IsUserInRoleResponse(ServiceSSO.IsUserInRoleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class IsUserInRoleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUserInRoleResult;
        
        public IsUserInRoleResponseBody()
        {
        }
        
        public IsUserInRoleResponseBody(bool IsUserInRoleResult)
        {
            this.IsUserInRoleResult = IsUserInRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoleExistsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoleExists", Namespace="SSO", Order=0)]
        public ServiceSSO.RoleExistsRequestBody Body;
        
        public RoleExistsRequest()
        {
        }
        
        public RoleExistsRequest(ServiceSSO.RoleExistsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class RoleExistsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleName;
        
        public RoleExistsRequestBody()
        {
        }
        
        public RoleExistsRequestBody(string appName, string roleName)
        {
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoleExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoleExistsResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.RoleExistsResponseBody Body;
        
        public RoleExistsResponse()
        {
        }
        
        public RoleExistsResponse(ServiceSSO.RoleExistsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class RoleExistsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RoleExistsResult;
        
        public RoleExistsResponseBody()
        {
        }
        
        public RoleExistsResponseBody(bool RoleExistsResult)
        {
            this.RoleExistsResult = RoleExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToken", Namespace="SSO", Order=0)]
        public ServiceSSO.DeleteTokenRequestBody Body;
        
        public DeleteTokenRequest()
        {
        }
        
        public DeleteTokenRequest(ServiceSSO.DeleteTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class DeleteTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public DeleteTokenRequestBody()
        {
        }
        
        public DeleteTokenRequestBody(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTokenResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.DeleteTokenResponseBody Body;
        
        public DeleteTokenResponse()
        {
        }
        
        public DeleteTokenResponse(ServiceSSO.DeleteTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteTokenResponseBody
    {
        
        public DeleteTokenResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessForUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessForUser", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAccessForUserRequestBody Body;
        
        public GetAccessForUserRequest()
        {
        }
        
        public GetAccessForUserRequest(ServiceSSO.GetAccessForUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccessForUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string formName;
        
        public GetAccessForUserRequestBody()
        {
        }
        
        public GetAccessForUserRequestBody(string username, string appName, string formName)
        {
            this.username = username;
            this.appName = appName;
            this.formName = formName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessForUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessForUserResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAccessForUserResponseBody Body;
        
        public GetAccessForUserResponse()
        {
        }
        
        public GetAccessForUserResponse(ServiceSSO.GetAccessForUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccessForUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessForUserResult;
        
        public GetAccessForUserResponseBody()
        {
        }
        
        public GetAccessForUserResponseBody(string GetAccessForUserResult)
        {
            this.GetAccessForUserResult = GetAccessForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="SSO", Order=0)]
        public ServiceSSO.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(ServiceSSO.ChangePasswordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ChangePasswordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OdlPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NewPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserId;
        
        public ChangePasswordRequestBody()
        {
        }
        
        public ChangePasswordRequestBody(string OdlPass, string NewPass, string UserId)
        {
            this.OdlPass = OdlPass;
            this.NewPass = NewPass;
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(ServiceSSO.ChangePasswordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ChangePasswordResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody()
        {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult)
        {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserType", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUserTypeRequestBody Body;
        
        public GetUserTypeRequest()
        {
        }
        
        public GetUserTypeRequest(ServiceSSO.GetUserTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        public GetUserTypeRequestBody()
        {
        }
        
        public GetUserTypeRequestBody(string userid)
        {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserTypeResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUserTypeResponseBody Body;
        
        public GetUserTypeResponse()
        {
        }
        
        public GetUserTypeResponse(ServiceSSO.GetUserTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserTypeResult;
        
        public GetUserTypeResponseBody()
        {
        }
        
        public GetUserTypeResponseBody(string GetUserTypeResult)
        {
            this.GetUserTypeResult = GetUserTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllowModulRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllowModul", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAllowModulRequestBody Body;
        
        public GetAllowModulRequest()
        {
        }
        
        public GetAllowModulRequest(ServiceSSO.GetAllowModulRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllowModulRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Modul;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Access;
        
        public GetAllowModulRequestBody()
        {
        }
        
        public GetAllowModulRequestBody(string UserId, string Modul, int Access)
        {
            this.UserId = UserId;
            this.Modul = Modul;
            this.Access = Access;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllowModulResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllowModulResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAllowModulResponseBody Body;
        
        public GetAllowModulResponse()
        {
        }
        
        public GetAllowModulResponse(ServiceSSO.GetAllowModulResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllowModulResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetAllowModulResult;
        
        public GetAllowModulResponseBody()
        {
        }
        
        public GetAllowModulResponseBody(bool GetAllowModulResult)
        {
            this.GetAllowModulResult = GetAllowModulResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccesExtendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccesExtend", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAccesExtendRequestBody Body;
        
        public GetAccesExtendRequest()
        {
        }
        
        public GetAccesExtendRequest(ServiceSSO.GetAccesExtendRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccesExtendRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Extid;
        
        public GetAccesExtendRequestBody()
        {
        }
        
        public GetAccesExtendRequestBody(string UserId, int Extid)
        {
            this.UserId = UserId;
            this.Extid = Extid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccesExtendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccesExtendResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.GetAccesExtendResponseBody Body;
        
        public GetAccesExtendResponse()
        {
        }
        
        public GetAccesExtendResponse(ServiceSSO.GetAccesExtendResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccesExtendResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetAccesExtendResult;
        
        public GetAccesExtendResponseBody()
        {
        }
        
        public GetAccesExtendResponseBody(bool GetAccesExtendResult)
        {
            this.GetAccesExtendResult = GetAccesExtendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccGroupUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccGroupUser", Namespace="SSO", Order=0)]
        public ServiceSSO.CheckAccGroupUserRequestBody Body;
        
        public CheckAccGroupUserRequest()
        {
        }
        
        public CheckAccGroupUserRequest(ServiceSSO.CheckAccGroupUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CheckAccGroupUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccGroup;
        
        public CheckAccGroupUserRequestBody()
        {
        }
        
        public CheckAccGroupUserRequestBody(string UserId, string AccGroup)
        {
            this.UserId = UserId;
            this.AccGroup = AccGroup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccGroupUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccGroupUserResponse", Namespace="SSO", Order=0)]
        public ServiceSSO.CheckAccGroupUserResponseBody Body;
        
        public CheckAccGroupUserResponse()
        {
        }
        
        public CheckAccGroupUserResponse(ServiceSSO.CheckAccGroupUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CheckAccGroupUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckAccGroupUserResult;
        
        public CheckAccGroupUserResponseBody()
        {
        }
        
        public CheckAccGroupUserResponseBody(bool CheckAccGroupUserResult)
        {
            this.CheckAccGroupUserResult = CheckAccGroupUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitV2", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUserUnitV2RequestBody Body;
        
        public GetUserUnitV2Request()
        {
        }
        
        public GetUserUnitV2Request(ServiceSSO.GetUserUnitV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserUnitV2RequestBody()
        {
        }
        
        public GetUserUnitV2RequestBody(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitV2Response", Namespace="SSO", Order=0)]
        public ServiceSSO.GetUserUnitV2ResponseBody Body;
        
        public GetUserUnitV2Response()
        {
        }
        
        public GetUserUnitV2Response(ServiceSSO.GetUserUnitV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserUnitV2Result;
        
        public GetUserUnitV2ResponseBody()
        {
        }
        
        public GetUserUnitV2ResponseBody(string GetUserUnitV2Result)
        {
            this.GetUserUnitV2Result = GetUserUnitV2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SSOWSSoapChannel : ServiceSSO.SSOWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SSOWSSoapClient : System.ServiceModel.ClientBase<ServiceSSO.SSOWSSoap>, ServiceSSO.SSOWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SSOWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SSOWSSoapClient.GetBindingForEndpoint(endpointConfiguration), SSOWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SSOWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SSOWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.ValidateUserResponse> ServiceSSO.SSOWSSoap.ValidateUserAsync(ServiceSSO.ValidateUserRequest request)
        {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.ValidateUserResponse> ValidateUserAsync(string username, string password)
        {
            ServiceSSO.ValidateUserRequest inValue = new ServiceSSO.ValidateUserRequest();
            inValue.Body = new ServiceSSO.ValidateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceSSO.SSOWSSoap)(this)).ValidateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.ValidateUser_2Response> ServiceSSO.SSOWSSoap.ValidateUser_2Async(ServiceSSO.ValidateUser_2Request request)
        {
            return base.Channel.ValidateUser_2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.ValidateUser_2Response> ValidateUser_2Async(string username, string password)
        {
            ServiceSSO.ValidateUser_2Request inValue = new ServiceSSO.ValidateUser_2Request();
            inValue.Body = new ServiceSSO.ValidateUser_2RequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceSSO.SSOWSSoap)(this)).ValidateUser_2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.ValidateUserGetNIPResponse> ServiceSSO.SSOWSSoap.ValidateUserGetNIPAsync(ServiceSSO.ValidateUserGetNIPRequest request)
        {
            return base.Channel.ValidateUserGetNIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.ValidateUserGetNIPResponse> ValidateUserGetNIPAsync(string username, string password)
        {
            ServiceSSO.ValidateUserGetNIPRequest inValue = new ServiceSSO.ValidateUserGetNIPRequest();
            inValue.Body = new ServiceSSO.ValidateUserGetNIPRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceSSO.SSOWSSoap)(this)).ValidateUserGetNIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.CreateTokenResponse> ServiceSSO.SSOWSSoap.CreateTokenAsync(ServiceSSO.CreateTokenRequest request)
        {
            return base.Channel.CreateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.CreateTokenResponse> CreateTokenAsync(string username, string token)
        {
            ServiceSSO.CreateTokenRequest inValue = new ServiceSSO.CreateTokenRequest();
            inValue.Body = new ServiceSSO.CreateTokenRequestBody();
            inValue.Body.username = username;
            inValue.Body.token = token;
            return ((ServiceSSO.SSOWSSoap)(this)).CreateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.VerifyResponse> ServiceSSO.SSOWSSoap.VerifyAsync(ServiceSSO.VerifyRequest request)
        {
            return base.Channel.VerifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.VerifyResponse> VerifyAsync(string username, string token)
        {
            ServiceSSO.VerifyRequest inValue = new ServiceSSO.VerifyRequest();
            inValue.Body = new ServiceSSO.VerifyRequestBody();
            inValue.Body.username = username;
            inValue.Body.token = token;
            return ((ServiceSSO.SSOWSSoap)(this)).VerifyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetUserUnitResponse> ServiceSSO.SSOWSSoap.GetUserUnitAsync(ServiceSSO.GetUserUnitRequest request)
        {
            return base.Channel.GetUserUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetUserUnitResponse> GetUserUnitAsync(string username)
        {
            ServiceSSO.GetUserUnitRequest inValue = new ServiceSSO.GetUserUnitRequest();
            inValue.Body = new ServiceSSO.GetUserUnitRequestBody();
            inValue.Body.username = username;
            return ((ServiceSSO.SSOWSSoap)(this)).GetUserUnitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetAllRolesResponse> ServiceSSO.SSOWSSoap.GetAllRolesAsync(ServiceSSO.GetAllRolesRequest request)
        {
            return base.Channel.GetAllRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetAllRolesResponse> GetAllRolesAsync(string appName)
        {
            ServiceSSO.GetAllRolesRequest inValue = new ServiceSSO.GetAllRolesRequest();
            inValue.Body = new ServiceSSO.GetAllRolesRequestBody();
            inValue.Body.appName = appName;
            return ((ServiceSSO.SSOWSSoap)(this)).GetAllRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetRolesForUserResponse> ServiceSSO.SSOWSSoap.GetRolesForUserAsync(ServiceSSO.GetRolesForUserRequest request)
        {
            return base.Channel.GetRolesForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetRolesForUserResponse> GetRolesForUserAsync(string username, string appName)
        {
            ServiceSSO.GetRolesForUserRequest inValue = new ServiceSSO.GetRolesForUserRequest();
            inValue.Body = new ServiceSSO.GetRolesForUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            return ((ServiceSSO.SSOWSSoap)(this)).GetRolesForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetUsersInRoleResponse> ServiceSSO.SSOWSSoap.GetUsersInRoleAsync(ServiceSSO.GetUsersInRoleRequest request)
        {
            return base.Channel.GetUsersInRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetUsersInRoleResponse> GetUsersInRoleAsync(string appName, string roleName)
        {
            ServiceSSO.GetUsersInRoleRequest inValue = new ServiceSSO.GetUsersInRoleRequest();
            inValue.Body = new ServiceSSO.GetUsersInRoleRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            return ((ServiceSSO.SSOWSSoap)(this)).GetUsersInRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.IsUserInRoleResponse> ServiceSSO.SSOWSSoap.IsUserInRoleAsync(ServiceSSO.IsUserInRoleRequest request)
        {
            return base.Channel.IsUserInRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.IsUserInRoleResponse> IsUserInRoleAsync(string username, string appName, string roleName)
        {
            ServiceSSO.IsUserInRoleRequest inValue = new ServiceSSO.IsUserInRoleRequest();
            inValue.Body = new ServiceSSO.IsUserInRoleRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            return ((ServiceSSO.SSOWSSoap)(this)).IsUserInRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.RoleExistsResponse> ServiceSSO.SSOWSSoap.RoleExistsAsync(ServiceSSO.RoleExistsRequest request)
        {
            return base.Channel.RoleExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.RoleExistsResponse> RoleExistsAsync(string appName, string roleName)
        {
            ServiceSSO.RoleExistsRequest inValue = new ServiceSSO.RoleExistsRequest();
            inValue.Body = new ServiceSSO.RoleExistsRequestBody();
            inValue.Body.appName = appName;
            inValue.Body.roleName = roleName;
            return ((ServiceSSO.SSOWSSoap)(this)).RoleExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.DeleteTokenResponse> ServiceSSO.SSOWSSoap.DeleteTokenAsync(ServiceSSO.DeleteTokenRequest request)
        {
            return base.Channel.DeleteTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.DeleteTokenResponse> DeleteTokenAsync(string username)
        {
            ServiceSSO.DeleteTokenRequest inValue = new ServiceSSO.DeleteTokenRequest();
            inValue.Body = new ServiceSSO.DeleteTokenRequestBody();
            inValue.Body.username = username;
            return ((ServiceSSO.SSOWSSoap)(this)).DeleteTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetAccessForUserResponse> ServiceSSO.SSOWSSoap.GetAccessForUserAsync(ServiceSSO.GetAccessForUserRequest request)
        {
            return base.Channel.GetAccessForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetAccessForUserResponse> GetAccessForUserAsync(string username, string appName, string formName)
        {
            ServiceSSO.GetAccessForUserRequest inValue = new ServiceSSO.GetAccessForUserRequest();
            inValue.Body = new ServiceSSO.GetAccessForUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.appName = appName;
            inValue.Body.formName = formName;
            return ((ServiceSSO.SSOWSSoap)(this)).GetAccessForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.ChangePasswordResponse> ServiceSSO.SSOWSSoap.ChangePasswordAsync(ServiceSSO.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.ChangePasswordResponse> ChangePasswordAsync(string OdlPass, string NewPass, string UserId)
        {
            ServiceSSO.ChangePasswordRequest inValue = new ServiceSSO.ChangePasswordRequest();
            inValue.Body = new ServiceSSO.ChangePasswordRequestBody();
            inValue.Body.OdlPass = OdlPass;
            inValue.Body.NewPass = NewPass;
            inValue.Body.UserId = UserId;
            return ((ServiceSSO.SSOWSSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetUserTypeResponse> ServiceSSO.SSOWSSoap.GetUserTypeAsync(ServiceSSO.GetUserTypeRequest request)
        {
            return base.Channel.GetUserTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetUserTypeResponse> GetUserTypeAsync(string userid)
        {
            ServiceSSO.GetUserTypeRequest inValue = new ServiceSSO.GetUserTypeRequest();
            inValue.Body = new ServiceSSO.GetUserTypeRequestBody();
            inValue.Body.userid = userid;
            return ((ServiceSSO.SSOWSSoap)(this)).GetUserTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetAllowModulResponse> ServiceSSO.SSOWSSoap.GetAllowModulAsync(ServiceSSO.GetAllowModulRequest request)
        {
            return base.Channel.GetAllowModulAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetAllowModulResponse> GetAllowModulAsync(string UserId, string Modul, int Access)
        {
            ServiceSSO.GetAllowModulRequest inValue = new ServiceSSO.GetAllowModulRequest();
            inValue.Body = new ServiceSSO.GetAllowModulRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.Modul = Modul;
            inValue.Body.Access = Access;
            return ((ServiceSSO.SSOWSSoap)(this)).GetAllowModulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetAccesExtendResponse> ServiceSSO.SSOWSSoap.GetAccesExtendAsync(ServiceSSO.GetAccesExtendRequest request)
        {
            return base.Channel.GetAccesExtendAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetAccesExtendResponse> GetAccesExtendAsync(string UserId, int Extid)
        {
            ServiceSSO.GetAccesExtendRequest inValue = new ServiceSSO.GetAccesExtendRequest();
            inValue.Body = new ServiceSSO.GetAccesExtendRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.Extid = Extid;
            return ((ServiceSSO.SSOWSSoap)(this)).GetAccesExtendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.CheckAccGroupUserResponse> ServiceSSO.SSOWSSoap.CheckAccGroupUserAsync(ServiceSSO.CheckAccGroupUserRequest request)
        {
            return base.Channel.CheckAccGroupUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.CheckAccGroupUserResponse> CheckAccGroupUserAsync(string UserId, string AccGroup)
        {
            ServiceSSO.CheckAccGroupUserRequest inValue = new ServiceSSO.CheckAccGroupUserRequest();
            inValue.Body = new ServiceSSO.CheckAccGroupUserRequestBody();
            inValue.Body.UserId = UserId;
            inValue.Body.AccGroup = AccGroup;
            return ((ServiceSSO.SSOWSSoap)(this)).CheckAccGroupUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceSSO.GetUserUnitV2Response> ServiceSSO.SSOWSSoap.GetUserUnitV2Async(ServiceSSO.GetUserUnitV2Request request)
        {
            return base.Channel.GetUserUnitV2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceSSO.GetUserUnitV2Response> GetUserUnitV2Async(string username)
        {
            ServiceSSO.GetUserUnitV2Request inValue = new ServiceSSO.GetUserUnitV2Request();
            inValue.Body = new ServiceSSO.GetUserUnitV2RequestBody();
            inValue.Body.username = username;
            return ((ServiceSSO.SSOWSSoap)(this)).GetUserUnitV2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://sso.pertaminaretail.com/SSOWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://sso.pertaminaretail.com/SSOWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SSOWSSoap,
            
            SSOWSSoap12,
        }
    }
}
